train:
  output_dir: "./model2"
  data_dir: "./data/raw/kaggle/kermany2018/OCT2017/train"
  valid_data_dir: "./data/raw/kaggle/kermany2018/OCT2017/val"
  schedule_sampler: uniform
  lr: 0.0001
  lr_decay: 0.98
  weight_decay: 0
  lr_anneal_steps: 0
  batch_size: 8
  microbatch: 4
  ema_rate: '0.9999'
  log_interval: 10
  save_interval: 100
  output_interval: 100
  resume_checkpoint: '/home/mlmi-kristina/mlmi-oct-diffusion/model2/model021500.pt'
  fp16_scale_growth: 0.001
  max_train_steps: 100000
  reference_samples_path: "./KAGGLE_OCT_TEST_GT.npz"
  save_only_best_model: True
  save_metric: loss
  max_patience: 1000
  #early_stopping_on: loss # To use early stoping, uncomment this line
data:
  resize_image: True
  resize_res: 128
  random_crop: True
  center_crop: False
sample:
  clip_denoised: True
  num_samples: 8
  batch_size: 8
  use_ddim: False
  model_path: ""
model:
  image_size: 256
  num_channels: 128
  num_res_blocks: 2
  num_heads: 1
  num_heads_upsample: -1
  num_head_channels: -1
  attention_resolutions: "16"
  channel_mult: ""
  dropout: 0.0
  class_cond: False
  use_checkpoint: False
  use_scale_shift_norm: False
  resblock_updown: False
  use_fp16: False
  use_new_attention_order: False
diffusion:
  learn_sigma: True
  diffusion_steps: 250
  noise_schedule: "linear"
  timestep_respacing: ""
  use_kl: False
  use_l1: False
  predict_xstart: False
  rescale_timesteps: False
  rescale_learned_sigmas: False
